#Minimum time in ticks for leaf decay. Must be lower than MaximumDecayTime!
MinimumDecayTime = 4
#Maximum time in ticks for leaf decay. Must be higher than MinimumDecayTime!
MaximumDecayTime = 11

